on: [push]

jobs:
  linter:
    runs-on: codeberg-tiny
    container:
      image: golangci/golangci-lint:latest
    
    steps:
      - name: Install Node.js
        run: apt update && apt install -y nodejs

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run linter
        run: make lint

  e2e:
    name: End to end tests
    runs-on: codeberg-tiny
    container:
      image: mcr.microsoft.com/playwright:v1.50.1-noble

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm i

      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Install Make
        run: apt update && apt install -y make

      - name: Build and start Filesender
        run: |
          CGO_ENABLED=1 make filesender
          ./filesender &
          sleep 5 # Wait for the server to start

      - name: Run playwright tests
        run: npx playwright test

      - name: Stop filesender
        run: pkill filesender || true
